### ISSUE TITLE
How to determine if an input image is anomalous based on the score?

### ISSUE THREAD

**Issue by Yi-Yang355** [LucStrater/GeneralAD#1]
Thank you for your contribution. When I want to predict whether an image is anomalous, how can I determine if the image is anomalous based on the model's output scores? as I do not need a visual heatmap.

**Comment by SMSD75** [comment]
Hi,

For each application, we can choose a specific threshold as the cutoff point between normal and abnormal inputs.  We reported AUROC, which reports an average performance for all possible thresholds.

**Comment by SMSD75** [comment]
I will close this issue since the problem seems to have been resolved.
