### ISSUE TITLE
About the Discriminator Output and ROC AUC Calculation

### ISSUE THREAD

**Issue by happyday521** [LucStrater/GeneralAD#4]
I've noticed that in the implementation, `scores = self.discriminator(features)`, where the output of the discriminator is directly used to compute the ROC AUC score. I'm curious why the output is not passed through a sigmoid function to convert the results into a value between 0 and 1 before calculating the ROC AUC score.

Using a sigmoid function typically helps in interpreting the output as probabilities, which seems essential for metrics like ROC AUC that evaluate the performance of a binary classifier. Could you please clarify the rationale behind this approach? Is there a specific reason for not applying the sigmoid transformation in this case?

Thanks！

**Comment by SMSD75** [comment]
Hi, thank you for pointing that out. You're absolutely right—this setup has the potential to further improve our results. We'll run some experiments to evaluate the impact, but please feel free to share your results if you’ve already explored this approach.
